# nginx/nginx.conf

# 1. Definimos nuestros backends internos.
upstream django_v1 {
    server web:8000;
}

upstream flask_v2 {
    server pagos_flask:5000;
}

log_format strangler '$remote_addr - $request -> upstream=$upstream_addr '
                     'status=$status upstream_status=$upstream_status';

server {
    listen 80;
    access_log /var/log/nginx/access.log strangler;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /api/v1/ {
        proxy_pass http://django_v1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location = /api/v2/comprar {
        proxy_pass http://flask_v2;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location = /api/v2/comprar/ {
        proxy_pass http://flask_v2;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://django_v1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
